Repository segment-oj/segmentoj, pull requests merged in 2020-08, with the labels that each got.

#20 Extract user introduction ztl
  account/migrations/0007_user_list_column.py
  account/models.py
  account/serializers.py
  account/tests.py
  account/views.py
  segmentoj/urls.py
Labels: Performance Improvements, good first issue

#21 Improve captcha ztl
  captcha/FiraCode-Regular.ttf
  captcha/apps.py
  captcha/tests.py
  captcha/tools.py
Labels: In Progress/正在修复, Low Priority, UX Improvements

#23 fix 500 at base64 decode
  account/views.py
Labels: bug

#24 Fix response ztl
  account/tests.py
  account/views.py
  problem/serializers.py
  problem/views.py
Labels: bug, good first issue

#30 fix status list count bug
  problem/views.py
  status/views.py
Labels: High Priority, UX Improvements, enhancement/功能请求, good first issue
